### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;

### ISSUE THREAD

**Issue by yunheli** [irvingc/dbscan-on-spark#11]

**Comment by yunheli** [comment]
@irvingc 怎么解决啊

**Comment by tovbinm** [comment]
This is most likely due to wrong Scala / Spark version.

**Comment by BhaveshMandalkar** [comment]
So which is the correct version to solve this issue?

**Comment by tovbinm** [comment]
I think it was compiled to work with Spark 2.1.0.

**Comment by joydevg1** [comment]
Can you please help me more. Bcoz I build the jar against spark 2.1.0 but still the same error. Please tell me what's wrong in my pom dependency.
	<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>2.10.4</version>
		</dependency> 
		
	 <dependency>
	    <groupId>org.scala-lang</groupId>
	    <artifactId>scala-compiler</artifactId>
	    <version>2.10.4</version>
	</dependency>
				
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-mllib_2.10</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.meetup</groupId>
			<artifactId>archery_2.10</artifactId>
			<version>0.3.0</version>
		</dependency>
<dependency>
    <groupId>org.scalatest</groupId>
    <artifactId>scalatest_2.10</artifactId>
    <version>3.2.0-SNAP5</version>
    <scope>test</scope>
</dependency>
		
		<dependency>
		<groupId>com.irvingc.spark</groupId>
		<artifactId>dbscan_2.10</artifactId>
		<version>0.1.0</version>
	</dependency>
	
		 <dependency>     
		 <groupId>org.apache.spark</groupId>   
		   <artifactId>spark-core_2.10</artifactId>
		        <version>2.1.0</version>
		         </dependency>
		         
		       <dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.10</artifactId>
			<version>2.1.0</version>

**Comment by BhaveshMandalkar** [comment]
Can you please help me more. I am build the jar against spark 2.1.0 but still get the error. Please tell what's wrong in my pom.xml.

<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>2.10.4</version>
		</dependency> 
		
	 <dependency>
	    <groupId>org.scala-lang</groupId>
	    <artifactId>scala-compiler</artifactId>
	    <version>2.10.4</version>
	</dependency>
				
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-mllib_2.10</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.meetup</groupId>
			<artifactId>archery_2.10</artifactId>
			<version>0.3.0</version>
		</dependency>
<dependency>
    <groupId>org.scalatest</groupId>
    <artifactId>scalatest_2.10</artifactId>
    <version>3.2.0-SNAP5</version>
    <scope>test</scope>
</dependency>
		
		<dependency>
		<groupId>com.irvingc.spark</groupId>
		<artifactId>dbscan_2.10</artifactId>
		<version>0.1.0</version>
	</dependency>
	
		 <dependency>     
		 <groupId>org.apache.spark</groupId>   
		   <artifactId>spark-core_2.10</artifactId>
		        <version>2.1.0</version>
		         </dependency>
		         		
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.10</artifactId>
			<version>2.1.0</version>
		</dependency>
